# Game Theory Agents

In [1]:
import numpy as np
from game_simulation import simulate_match_up
from agent import *
from game import get_default_game, Game

## Define your own Agent

In [2]:
class MyAgent(Agent):
    """ Define your own Agent """
    def __init__(self, player_id, game):
        super().__init__(player_id, game)

    def get_action(self, last_action_p1, last_action_p2) -> Action:
        return Action.Defect
        raise NotImplementedError("Agent behaviour not yet implemented!")

## Test your agent against a specific bot.




In [9]:
GAMES_PER_MATCHUP = 100
game = get_default_game()  # or define your own using Game()  (see game.py for details)
print(game, "\n")

# evaluate a specific match-up, e.g. MyAgent vs. CopycatAgent  (index 1 vs index 2)
agents=[MyAgent, CopycatAgent]
print(f"{agents[0](1,game)} vs. {agents[1](1,game)} -> {simulate_match_up(agents[0], agents[1], game, GAMES_PER_MATCHUP)}")   

Game Payoff matrixes:
player 1 payoff: 
           Cooperate  Defect
Cooperate          2      -1
Defect             3       0

player 2 payoff: 
           Cooperate  Defect
Cooperate          2       3
Defect            -1       0 

MyAgent vs. CopycatAgent -> (3, -1)


## Simulate a small tournament

Play out all combinations of agents. The following agents are available:
- AllCooperateAgent
- AllDefectAgent
- CopycatAgent
- RandomAgent
- GrudgerAgent
- DetectiveAgent

Add your agent to the list in the first line to test it against all other agents.

In [4]:

agents = [MyAgent, AllCooperateAgent, AllDefectAgent, CopycatAgent, RandomAgent, GrudgerAgent, DetectiveAgent]
results = np.zeros((2, len(agents), len(agents)))
for id1, player1 in enumerate(agents):
    for id2, player2 in enumerate(agents):
        results[:, id1, id2] = simulate_match_up(player1, player2, game, GAMES_PER_MATCHUP)
print(results, "\n")
# results[:, agent1, agent2] contains the results of simulate_match_up(agent1, agent2, game)

for id, agent in enumerate(agents):
    print(f"total points of agent: {agent(1,game)} = {sum(results[0,id,:]) + sum(results[1,:,id])}")

[[[   0.  300.    0.    3.  135.    3.    6.]
  [-100.  200. -100.  200.   53.  200.  -94.]
  [   0.  300.    0.    3.  150.    3.    6.]
  [  -1.  200.   -1.  200.  114.  200.   99.]
  [ -51.  254.  -53.  109.  107.  -57.  112.]
  [  -1.  200.   -1.  200.  144.  200.    4.]
  [  -2.  298.   -2.  103.  108.    4.  198.]]

 [[   0. -100.    0.   -1.  -45.   -1.   -2.]
  [ 300.  200.  300.  200.  249.  200.  298.]
  [   0. -100.    0.   -1.  -50.   -1.   -2.]
  [   3.  200.    3.  200.  114.  200.  103.]
  [ 153.   38.  159.  105.  103.  179.  112.]
  [   3.  200.    3.  200.  -40.  200.    4.]
  [   6.  -94.    6.   99.  116.    4.  198.]]] 

total points of agent: MyAgent = 912.0
total points of agent: AllCooperateAgent = 703.0
total points of agent: AllDefectAgent = 933.0
total points of agent: CopycatAgent = 1613.0
total points of agent: RandomAgent = 868.0
total points of agent: GrudgerAgent = 1527.0
total points of agent: DetectiveAgent = 1418.0
